// <auto-generated />
using System;
using MVC_Webshop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Webshop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
    [Migration("20230123151616_wwwwwwwww")]
    partial class wwwwwwwww
========
    [Migration("20230124165044_init")]
    partial class init
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 2
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 3
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            Id = "6c754753-efe8-49c9-9988-fb46165b6a6b",
                            ConcurrencyStamp = "5c88a13c-bd41-4915-b3a2-5dda9a78b236",
========
                            Id = "b59e4b4b-a157-41a6-b6d9-abc84834529f",
                            ConcurrencyStamp = "af857470-6eb9-4b8c-98e0-3c9145279bfd",
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            Id = "17e89352-86f8-4138-8352-03640369af8f",
                            ConcurrencyStamp = "74da152f-a44d-497a-b985-cc733558f97b",
========
                            Id = "a2534b98-d03e-4de0-bb0f-f00a9772ddbc",
                            ConcurrencyStamp = "5198bdb7-6e7a-4bd7-8a7b-7cbe3a6fdda4",
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            Id = "f5e1eb4f-6079-4b17-88a9-0b35e22a2685",
                            ConcurrencyStamp = "94c4860f-eb84-42ac-bbff-850a71ebda8e",
========
                            Id = "53db8c92-a481-4464-95e0-d93fb45c8195",
                            ConcurrencyStamp = "136717fd-aed6-4f4f-a713-005b088d88d4",
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            UserId = "17e89352-86f8-4138-8352-03640369af8f",
                            RoleId = "6c754753-efe8-49c9-9988-fb46165b6a6b"
                        },
                        new
                        {
                            UserId = "17e89352-86f8-4138-8352-03640369af8f",
                            RoleId = "f5e1eb4f-6079-4b17-88a9-0b35e22a2685"
                        },
                        new
                        {
                            UserId = "17e89352-86f8-4138-8352-03640369af8f",
                            RoleId = "17e89352-86f8-4138-8352-03640369af8f"
========
                            UserId = "a2534b98-d03e-4de0-bb0f-f00a9772ddbc",
                            RoleId = "b59e4b4b-a157-41a6-b6d9-abc84834529f"
                        },
                        new
                        {
                            UserId = "a2534b98-d03e-4de0-bb0f-f00a9772ddbc",
                            RoleId = "53db8c92-a481-4464-95e0-d93fb45c8195"
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MVC_Webshop.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CartId")
                        .IsUnique()
                        .HasFilter("[CartId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            Id = "6c754753-efe8-49c9-9988-fb46165b6a6b",
                            AccessFailedCount = 0,
                            CartId = 1,
                            ConcurrencyStamp = "bcc35a65-e11a-4a75-9f23-4da61ea8d9b0",
========
                            Id = "a2534b98-d03e-4de0-bb0f-f00a9772ddbc",
                            AccessFailedCount = 0,
                            CartId = 1,
                            ConcurrencyStamp = "773328d7-934e-4122-b66f-479333edbc81",
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                            CreditCardNumber = "234",
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Adminson",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN",
                            OrderId = 1,
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            PasswordHash = "AQAAAAEAACcQAAAAEDhlKP7cMWeaX/Taqb+NKE4q99gjIOxqjilvdGo7Z+JpEyhp9Jh+TF6chvQVozjtsQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5d73cd17-557c-43e7-8b6a-3587256fe7c3",
========
                            PasswordHash = "AQAAAAEAACcQAAAAEI+yR6jDY5arFhXEz2wDgSbznkEJ1Mx93QDmdjrByP/D7JPyxxVVAaGHZw3shRRg0w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "305adce2-7f15-4df2-97f8-df3b61976bdb",
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            Id = "f5e1eb4f-6079-4b17-88a9-0b35e22a2685",
                            AccessFailedCount = 0,
                            CartId = 2,
                            ConcurrencyStamp = "3f5fca7e-d50d-4f9b-9bf8-a6792ef35fcc",
========
                            Id = "53db8c92-a481-4464-95e0-d93fb45c8195",
                            AccessFailedCount = 0,
                            CartId = 2,
                            ConcurrencyStamp = "bcd87f8e-b3c6-41b8-929c-19e420450647",
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                            CreditCardNumber = "123",
                            Email = "karen@manager.com",
                            EmailConfirmed = false,
                            FirstName = "Karen",
                            LastName = "Managerson",
                            LockoutEnabled = false,
                            NormalizedEmail = "KAREN@MANAGER.COM",
                            NormalizedUserName = "KAREN",
                            OrderId = 2,
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            PasswordHash = "AQAAAAEAACcQAAAAEPzzE5NI7/R5K/M1g62nvgen8/Pn86n2SWb5RwZmRM9yjWEsX3FUaEYcahgs5oZ6/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d62efd82-f5f4-47c0-86d1-6dcb30c1c5cf",
========
                            PasswordHash = "AQAAAAEAACcQAAAAEB4eJ11usKcODZusRgz5SjEoKqJL2jBPfyIdfW3EZXvbWX9/yu9uzh8MQP+vTS8JaA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3d631e31-9153-4c31-90f0-8e967e1e7414",
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                            TwoFactorEnabled = false,
                            UserName = "Karen"
                        },
                        new
                        {
                            Id = "17e89352-86f8-4138-8352-03640369af8f",
                            AccessFailedCount = 0,
                            CartId = 3,
                            ConcurrencyStamp = "55e67838-302e-4b71-ace4-a17b7aa4dc77",
                            CreditCardNumber = "123",
                            Email = "random@user.com",
                            EmailConfirmed = false,
                            FirstName = "Joe",
                            LastName = "Sixpack",
                            LockoutEnabled = false,
                            NormalizedEmail = "RANDOM@USER.COM",
                            NormalizedUserName = "JOE",
                            OrderId = 3,
                            PasswordHash = "AQAAAAEAACcQAAAAEJeysC3SlYITR9pcvkuV8Wk9pUups3Ibm+0yZ1Qw8O5JIxudOJoxoqquvNB2BlhV4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3dfe5ee-81fe-4ba2-aa73-9944501ca744",
                            TwoFactorEnabled = false,
                            UserName = "Joe"
                        });
                });

            modelBuilder.Entity("MVC_Webshop.Models.Cart", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        });
                });

            modelBuilder.Entity("MVC_Webshop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Berry",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fruit",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drinks",
                            ProductId = 0
                        });
                });

            modelBuilder.Entity("MVC_Webshop.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductIdRef")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            ProductIdRef = 1,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("MVC_Webshop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ExpectedDelivery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Shipped")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            ExpectedDelivery = "3",
                            OrderDate = new DateTime(2023, 1, 23, 16, 16, 15, 723, DateTimeKind.Local).AddTicks(3868),
                            Shipped = false,
                            ShippingDate = new DateTime(2023, 1, 23, 16, 16, 15, 723, DateTimeKind.Local).AddTicks(3826)
========
                            ExpectedDelivery = "4",
                            OrderDate = new DateTime(2023, 1, 24, 17, 50, 43, 373, DateTimeKind.Local).AddTicks(5152),
                            Shipped = false,
                            ShippingDate = new DateTime(2023, 1, 24, 17, 50, 43, 373, DateTimeKind.Local).AddTicks(5009)
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            ExpectedDelivery = "3",
                            OrderDate = new DateTime(2023, 1, 23, 16, 16, 15, 723, DateTimeKind.Local).AddTicks(3887),
                            Shipped = false,
                            ShippingDate = new DateTime(2023, 1, 23, 16, 16, 15, 723, DateTimeKind.Local).AddTicks(3885)
                        },
                        new
                        {
                            Id = 3,
                            ExpectedDelivery = "3",
                            OrderDate = new DateTime(2023, 1, 23, 16, 16, 15, 723, DateTimeKind.Local).AddTicks(3899),
                            Shipped = false,
                            ShippingDate = new DateTime(2023, 1, 23, 16, 16, 15, 723, DateTimeKind.Local).AddTicks(3897)
========
                            ExpectedDelivery = "4",
                            OrderDate = new DateTime(2023, 1, 24, 17, 50, 43, 373, DateTimeKind.Local).AddTicks(5227),
                            Shipped = false,
                            ShippingDate = new DateTime(2023, 1, 24, 17, 50, 43, 373, DateTimeKind.Local).AddTicks(5224)
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                        });
                });

            modelBuilder.Entity("MVC_Webshop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MVC_Webshop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            Brand = "Birdstuff",
                            CategoryId = 1,
                            Description = "it's a type of bird",
                            ImageUrl = "/img/gerpgork.jpg",
                            Name = "Gerpgork",
                            Price = 2000.0,
                            Quantity = 1,
                            ShortDescription = "tb"
========
                            Brand = "Frukt & Grönt",
                            CategoryId = 0,
                            Description = "Dessa mangosar är plockade av elitpersonal djupt nere i den farliga mangodalen.",
                            ImageUrl = "/imagesProduct/8fa4535c-a692-4407-83f6-e74e4dcd903b_mango-01.jpg",
                            Name = "Mango",
                            Price = 5.0,
                            Quantity = 200,
                            ShortDescription = "Fina mango från Mangodalen"
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            Brand = "Chiquita",
                            CategoryId = 2,
                            Description = "it's a type of Banana",
                            ImageUrl = "/img/Banana.jpg",
                            Name = "Banana",
                            Price = 5.0,
                            Quantity = 1,
                            ShortDescription = "tb"
========
                            Brand = "Sura Gubben",
                            CategoryId = 0,
                            Description = "Dessa citroner som odlas på hemlig utomjordisk plats har den finaste och söta surhet som någonsin uppmätts i en citron.",
                            ImageUrl = "/imagesProduct/3aeac812-a431-4711-83b3-079816d8a7c1_lemon-01.jpg",
                            Name = "Citron",
                            Price = 4.7999999999999998,
                            Quantity = 800,
                            ShortDescription = "Färska och sura citroner"
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:MVC_Webshop/Migrations/20230123151616_wwwwwwwww.Designer.cs
                            Brand = "Volvo",
                            CategoryId = 3,
                            Description = "it's a type of car",
                            ImageUrl = "/img/Volvo.jpg",
                            Name = "Volvo XC70",
                            Price = 500000.0,
                            Quantity = 1,
                            ShortDescription = "tb"
========
                            Brand = "Äppelmannen & Co",
                            CategoryId = 0,
                            Description = "Dessa härliga äpplen är odlade av äppelmannen i hans trädgård. De är friska och alltid färska. Dessa bör man passa på att köpa när de finns eftersom de är svåra att få tag i när de inte finns.",
                            ImageUrl = "/imagesProduct/c8894c3b-9e69-4a34-97fd-3296ad428e49_apple-02.jpg",
                            Name = "Gröna äpplen",
                            Price = 6.0,
                            Quantity = 140,
                            ShortDescription = "Snabba äpplen med frisk smak"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Mr Blueberry",
                            CategoryId = 0,
                            Description = "Dessa bär smakar bäst efter att man mosat en näve bär i handen och sen slickar rent fingrarna..",
                            ImageUrl = "/imagesProduct/4b518a1f-27a4-4ad6-8996-ce900469135b_blueberry-01.jpg",
                            Name = "Blåbär",
                            Price = 0.040000000000000001,
                            Quantity = 1000000,
                            ShortDescription = "Små runda blåa blåbär"
>>>>>>>> origin/MikaelHomeCodeMerge01:MVC_Webshop/Migrations/20230124165044_init.Designer.cs
                        });
                });

            modelBuilder.Entity("MVC_Webshop.ViewModels.CategoryCreateViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryCreateViewModel");
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("MVC_Webshop.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Webshop.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MVC_Webshop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MVC_Webshop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Webshop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MVC_Webshop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVC_Webshop.Data.ApplicationUser", b =>
                {
                    b.HasOne("MVC_Webshop.Models.Cart", "Cart")
                        .WithOne("User")
                        .HasForeignKey("MVC_Webshop.Data.ApplicationUser", "CartId");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("MVC_Webshop.Models.Item", b =>
                {
                    b.HasOne("MVC_Webshop.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("MVC_Webshop.Models.Order", b =>
                {
                    b.HasOne("MVC_Webshop.Data.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_Webshop.Models.OrderItem", b =>
                {
                    b.HasOne("MVC_Webshop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MVC_Webshop.Data.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MVC_Webshop.Models.Cart", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_Webshop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
